/* University TABLE*/
DROP TABLE UNIVERSITY;
CREATE TABLE UNIVERSITY
       (UNIVERSITY_ID NUMBER (10),
    UNIVERSITY_ANAME VARCHAR2(500),
    UNIVERSITY_ENAME  VARCHAR2(500), 
    WEBSITE VARCHAR2(500), CONSTRAINT UNIVERSITY_PK PRIMARY KEY (UNIVERSITY_ID));

/*SELECT
    * FROM UNIVERSITY;
    DESC UNIVERSITY;*/

/*********************************************************/

/* SCHOOL TABLE*/
DROP TABLE SCHOOL;
CREATE TABLE SCHOOL 
       (SCHOOL_ID NUMBER(5),
    SCHOOL_ANAME VARCHAR2(500),
    SCHOOL_ENAME VARCHAR2(500), CONSTRAINT SCHOOL_PK PRIMARY KEY (SCHOOL_ID));

SELECT
    * FROM SCHOOL;
    
DESC SCHOOL;

/*********************************************************/

/* PROGRAM TABLE*/
DROP TABLE PROGRAM;
CREATE TABLE PROGRAM 
       (SCHOOL_ID NUMBER(5),
    PROGRAM_ID NUMBER(5),
    PROGRAM_ANAME VARCHAR2(500),
    PROGRAM_ENAME VARCHAR2(500),
    CONSTRAINT PROGRAM_PK PRIMARY KEY (SCHOOL_ID ,PROGRAM_ID), 
    CONSTRAINT SCHOOL_FK FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOL(SCHOOL_ID));

SELECT
    * FROM PROGRAM;
    
DESC PROGRAM;

/*********************************************************/

/*TRAINING_COURSE TABLE */
DROP TABLE TRAINING_COURSE;
CREATE TABLE TRAINING_COURSE 
       (COURSE_ID NUMBER(5),
    COURSE_ANAME VARCHAR2(500),
    COURSE_ENAME VARCHAR(500),
    MAX_STUDENTS NUMBER(5),
    SHORT_DESC VARCHAR(200),
    DETAILED_DESC VARCHAR(400),
    CONSTRAINT TRAINING_COURSE_PK PRIMARY KEY (COURSE_ID));

SELECT *
FROM TRAINING_COURSE;

DESC TRAINING_COURSE;

/*********************************************************/

/*STUDENT TABLE*/
DROP TABLE STUDENT;
CREATE TABLE STUDENT 
       (STUDENT_ID NUMBER(10), 
    UNIVERSITY_ID NUMBER(5),
    SCHOOL_ID NUMBER(5),
    PROGRAM_ID NUMBER(5),
    STUDENT_ANAME VARCHAR2(100),
    STUDENT_ENAME VARCHAR2(100),
    MOBILE VARCHAR2(20),
    BIRTHDATE DATE ,
    SEX NUMBER(1),
    EMAIL VARCHAR2(50),
    FINAL_AVERAGE NUMBER(7,2),
    MAX_AVERAGE NUMBER(7,2),
    RATE VARCHAR2(50),
    GRADUATE_YEAR NUMBER(4),
    GRADUATE_SUM NUMBER(1),
    CONSTRAINT STUDENT_PK PRIMARY KEY (UNIVERSITY_ID,SCHOOL_ID,PROGRAM_ID,STUDENT_ID),
    CONSTRAINT STUDENT_UNIVERSITY_FK FOREIGN KEY (UNIVERSITY_ID) REFERENCES UNIVERSITY(UNIVERSITY_ID),
    CONSTRAINT STUDENT_PROGRAM_FK FOREIGN KEY (SCHOOL_ID,PROGRAM_ID) REFERENCES PROGRAM(SCHOOL_ID,PROGRAM_ID));

SELECT
    * FROM STUDENT;
    
DESC STUDENT;

/*********************************************************/

/*STUDENT_TRAINING_COURSE*/
DROP TABLE STUDENT_TRAINING_COURSE;
CREATE TABLE STUDENT_TRAINING_COURSE 
       (STUDENT_ID NUMBER(10),
    COURSE_ID NUMBER (5), 
    PRIORITY NUMBER(5),
    CONSTRAINT STUDENT_TRAINING_COURSE_PK PRIMARY KEY (STUDENT_ID,COURSE_ID),
    CONSTRAINT STUDENT_TRAINING_COURSE_FK1 FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (STUDENT_ID),
    CONSTRAINT STUDENT_TRAINING_COURSE_FK2 FOREIGN KEY (COURSE_ID) REFERENCES TRAINING_COURSE (COURSE_ID));

SELECT
    * FROM STUDENT_TRAINING_COURSE;
    
DESC STUDENT_TRAINING_COURSE;

/*********************************************************/

/* TABLE STUDENT_RESULT */
DROP TABLE STUDENT_RESULT;
CREATE TABLE STUDENT_RESULT 
       (STUDENT_ID NUMBER (10),
    COURSE_ID NUMBER (5),
    ENGLISH_MARK NUMBER(7,2),
    INTERVIEW_MARK NUMBER(7,2),
    ACCEPTED_FLAG NUMBER(1),
    NOTES VARCHAR2(200),
    CONSTRAINT STUDENT_RESULT_PK PRIMARY KEY (STUDENT_ID),
    CONSTRAINT STUDENT_RESULT_FK FOREIGN KEY (STUDENT_ID,COURSE_ID) REFERENCES STUDENT_TRAINING_COURSE (STUDENT_ID,COURSE_ID));

SELECT
    * FROM STUDENT_RESULT;
    
DESC STUDENT_RESULT;

/*******************************************************************************/

COMMIT;

SET TERMOUT ON
SET ECHO ON